//! Build script: scans `<workspace>/presets/*.yaml` and emits a Rust file with
//! all preset bodies embedded as `&'static str`. The library code includes
//! the generated file via `include!`.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root resolvable")
        .to_path_buf();
    let presets_dir = workspace_root.join("presets");
    println!("cargo:rerun-if-changed={}", presets_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if let Ok(read_dir) = fs::read_dir(&presets_dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("yaml") {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("")
                .to_owned();
            if stem.is_empty() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            entries.push((stem, path));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::new();
    generated.push_str("// Auto-generated by build.rs — do not edit by hand.\n");
    generated.push_str("pub(crate) const PRESETS: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        let _ = writeln!(
            generated,
            "    ({:?}, include_str!({:?})),",
            name,
            path.to_string_lossy()
        );
    }
    generated.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by Cargo");
    let out_path = PathBuf::from(out_dir).join("presets_generated.rs");
    fs::write(&out_path, generated).expect("write generated presets file");
}
