[package]
name = "gc-forge-presets"
description = "Presets shipped with GC-Forge (embedded YAML)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
build = "build.rs"

[dependencies]
anyhow    = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }

[lints]
workspace = true
